name: Deploy IntelCrux to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Deploy Bot Service
      run: |
        cd bot
        npx @railway/cli login --token ${{ secrets.RAILWAY_TOKEN }}
        npx @railway/cli up --service intelcrux-bot

    - name: Deploy Dashboard Service
      run: |
        cd dashboard
        npx @railway/cli login --token ${{ secrets.RAILWAY_TOKEN }}
        npx @railway/cli up --service intelcrux-dashboard
